#!/usr/bin/env bash
#Script to display "bad luck from China" after 4th iteration
#display "bad luck from Japan" after 9th iteration
#display "bad luck from Italy" after 17th iteration

a=1
while [ $a -le 20 ]
do
	case $a in
	4) echo "$a"
	   echo "bad luck from China";;
	9) echo "$a"
	   echo "bad luck from Japan";;
	17) echo "$a"
	     echo "bad luck from Italy";;
	*) echo "$a"
	esac
	((a++))
done
